### PR TITLE
Reworked playlist items

### PR DESCRIPTION
**Pull request by bookdude13**
Instead of creating "Prepared" items when pre-loading the show, as well as having a really ugly 'prepare' function, the different items now all implement Runnable, contain their own data, and are prepped when they are created.

All of the boxing flying around is because traits (like Runnable) do not have a known size, so using them as interfaces means that all of the types implementing it must be wrapped in a Box (allocated on the heap and given a pointer). Also, you can apparently give the type of self as self: Box, which is a cool thing that I didn't know existed.

### CODE REVIEW

**Comment by bookdude13** [comment]
Recreated from #13, since a rebase was needed after #14 was merged.

**Comment by bookdude13** [comment]
Going to pull this in, since right now master cannot build and I haven't gotten any negative feedback from this PR

**Comment by kayla-e774** [comment]
Oh gosh, sorry I must've missed this request and I didn't keep up with GitHub very well recently. Again, very sorry.

Everything complies neatly on my end, also, in case you were curious :)

**Comment by bookdude13** [comment]
No problem :) Also, great to know that it works for you too!

**Pull request merged**
