### PR TITLE
Working code for 2016 show

### PR DESCRIPTION
**Pull request by bookdude13**
Pretty much the whole implementation of the runner in this pull request. I can break it up into a few smaller ones if desired. Mostly trying to get back to master, since I did a poor job syncing my branch with master during development.

### CODE REVIEW

**Comment by bookdude13** [comment]
Bump

**Review by computergeek125 — COMMENTED** [review]
proton_cli is "Downloads/proton_cli: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cc583398cfc5cb1c58b148e2be4125516c382767, not stripped"

**Comment by bookdude13** [comment]
Is that the binary you used? Did you have a problem running?

**Comment by computergeek125** [comment]
I found a binary in the repo.  You're not supposed to have binaries in a repo, since each system will built its own.  Normally binaries land in an `./out/` or `./bin/` directory that can be added to `.gitignore`

**Comment by bookdude13** [comment]
Ok, will move into an ignored ./bin directory. This can also be tweaked in PR #8 by providing the path to the proton_cli binary instead of copying it.

**Comment by bookdude13** [comment]
Got interesting "library not found" errors when running from the .bin directory. Ended up running `cargo install` on proton-cli, adding $HOME/.cargo/bin to my path, then assumed that the proton-cli binary could be found. This is cleaner anyway.

**Review by computergeek125 — APPROVED** [review]

**Pull request merged**
